site_name: Node.js
site_url: https://nodejsdev.ru/
site_description: Справочник web-разработчика с примерами кода - Node.js
site_author: nodejsdev.ru
copyright: (C) 2021, Справочник web-разработчика Node.js с примерами кода

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/nodejsdev.ru'

theme:
    name: material
    custom_dir: overrides
    # name: null
    # custom_dir: 'theme/material'
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: green
          accent: green
          toggle:
            icon: material/toggle-switch-off-outline
            name: Тёмная тема
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: green
          accent: green
          toggle:
            icon: material/toggle-switch
            name: Светлая тема
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
    favicon: nodejs.svg
    logo: nodejs-white.svg

extra:
    generator: false
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/nodejsdev_ru
          name: Группа в Telegram

#google_analytics:
#    - UA-34215161-1
#    - auto

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.keys

plugins:
    - search:
          lang:
              - ru
              - en
    - awesome-pages
    # - section-index
    - social

extra_css:
    - '/assets/stylesheets/styles.css'
